name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-deployment-img .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-deployment-img

      - name: Deploy to GCP
        run: |
          gcloud run deploy --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-deployment-img --platform managed --region ${{ secrets.GCP_REGION }}