name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: gcp-deployment-img

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Build
        run: ./build.sh

      - name: Login to GCR
        run: |
          gcloud auth configure-docker --projectId $PROJECT_ID

      - name: Build and Push Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy to GCP
        run: |
          # Deployment using kubectl (for GKE)
          kubectl apply -f deployment.yaml